FROM node:latest as node
WORKDIR /app
COPY . .
RUN npm install -g @angular/cli
RUN npm install
RUN ng build --configuration=test

FROM nginx:alpine
COPY --from=node /app/dist/browser /usr/share/nginx/html